language: node_js
env:
  global:
  - SFTP_USER=travis
  - SFTP_PASSWORD=travis123
  - secure: ZVaxGgJhWLQ5LSxKi8Mylg+QQju3HaJ0KCgurcJWd7DVs+nlEoRZtn4ldEiJdrFPNpjAx2/4XGXSFrpv9c45qd3Dx3pBYqKcWPY3pGAkAIj7zlUC2Jg7ISK7UWt2El1meVSoQJVq207DlJcEVIrBuFEx21z+5ZE7dK81y0fdiFmzEXpgUS0BU/Tkfze/FR60Q3oIUiQxvfDLddtIfQL5Sq3nxdtOu1m+UAh364ccund04EFGkG7ewklbUEfXb0SmbcLzbR3szB6UK0iXWzzI8JY9LLyAaGNlJiwsKWt7G6cj56ZZsgka4hygvSqUvJTEL5GXuwLoXkcmwzRDPiPj/1o2tkuwYrI10QciMWgVybtLqepbZZtBY4T+7XN/Ra/Ja/GSEwKN05G22z6h2nEqG7HgPMY43smB1Y9YgU8Yskicy8PpkjussNuM9wzV24K2jhvYUpLRx6uKojdwPzHbB4vXcy5JT2+1Ngeu6gYN16Nr0eM4nBHjnsJoq/5LaklNlK6d88z5LsNEe5ArZk1npmQQlG6wQSX3fBL172vTTvDjXVR6fQ2Yw7BqFo8TyWhDlBxZI3g+qFYFpO2HAjP5GpCZzRcMwWJrfeQ993Eg0R5mr9uJJW1OKbYU6MmTAi2VSoOOSeOaA4OQdTyhDHmlX+ueWTiYpKeXSCKJoZmnBk4=
  - secure: KTsaQTqzgst40k0/bzlV1IxT/m1W2TDqnwbYEcHY8aInuWAoEe/z8P70KohpFVfcahc0tJTt/vPiK4qV3+TK1Ayp9EjFC77x/w45gnzhDzMiI0NZy5V8WuLbLUYJfaWY3bjMrwED7NM8loZ3ifp94+8s5mAOkw0hnqhbd9DjV3BYDLqzQMy26pPKbBvFcLb7mMZeAeEpvWSosv42TyeVl97CE1N+C2rTZpdg4eKiro4JK2YQH1MkUAPlQllGDFmOJ+gIMJQ70DMbJJ2Vki0jvXyAq5H/g/gY5Qy4cdEML/nKRdNlvtqoeT7W/qBhF1yzbWoNeNjy5Jy9muCrZYqknogK1Em+D9Z/UGIT7AQekxrExl6LW9k48ylTEh5GHXkRxCcqVLTsMTolCRAecUgdTvd7RAWbPVTKsW8Hg3CP/U8rXVGQ17G6dPR+pZFrPrsKaz3sGHtJfNYVA78tKnGCe+hSx0kK3kOCkmcdKDuaDV6VyL70UJ0z3vD+Rte80UJKAjgI/HpKbfstBGDrFbFM7hUJTcCTZnKd7kZR+ws9cjzGcoPxga2px2Ub1e0nc2W8G0ri9UyD9XemkT3xB+Q19lGMATK78L3KZoZlqeU2/wgM4CpqrC9RgpAj7VJT2r8ExoStXKd6ksmMvFQjsAFkUxtn/3RjZTN+LKcTuT1DfgU=
  - secure: SW9iFUv/oPfMjRK+mff2dWxLsJEqx+kCoJwDoOOhiS1b8y1ttBBXmoC6c/pvwU3h7ZWGNPUnK34cm7lEhn19QwyzpF2lJ8clmhJHGa8PR+KU21JqQ9oGlxvtcwR43eVDta7pMJpKFW0odbAXALmW/KCfPT6I+QhBlv9UvP8qdHVTtldOAud8oHnF+PN/i2NiN66L31+nv6ndaMr0wGerqr5kcd34tv3mOvhmIedslVbl0PEDWCPoJDtigE9cL2PlO8YCGPdETJhC93y3rTUcH+NvW7SK6FUSD39WT1XtxS9IsdnlzRAJtxSYyAha6AWYUQSHIgw3FsnJeLjoT+M3GhvBv/t86AF8ZR2xl0JaILJflTHgmBA0yo7PE+bwm6mSL7HmmJKxeTJPs5fLKtGP5XG3b05arvMDVwQsJw/uYubIZFEpNjx/g4GToaRi82fhd89QMcdIua+AyWYG32O/FUoWRtbbQsQASCCFGkq/iXc2k/YjNNUUiuz3T7IxYLk0rs6X7d60iHK1lpzuA0aG86IiC0xWmRAnJbP4jyFAjmwCrjz8lyd9EK7F+nn/6evdQsyG0WscdJbEQ3pmkOi75FwG/7mRnYe9D2NhuNehSI1S9nIX0qLr+BsXeSHTrLjmZjSKcKNSGBtkPuOVtulr+uTl9H29ZvRpOmj4Es7G8dA=
  - secure: eRVus6uEtvng9gYdif6SNRMxo1DVlg4hxgh69h1s4VEx3HG1TYgkZYYW1GCa+U89zH4RAth/Hh1aotXu9+OcL4C70CVh0dw6xnswDUekjQxq3zi3SQQSrx66LhQzU4nTIS0XLdS/ZT3lEtg2tyuXKxpVNalVh8DwH4m582TEdyh4xxMx9r/Swm6K+VVq8J6t1UvEBEWjlDlQgm06KXVckAnM/6WJRZCVW39jFCVmCAWmM6XlJkC6q3n8FnPbXzGbdzEhNCIkq1FKnE8ZaYVRwz1Gnv8l1dEQuWvR+50/lohNaI72JyyiJdX9K/q7H7zEDUV1+iFNtNyFtsq6WPlcD5iROs0d97iqdPFtnFc2u/9XvQAtO1j+jI8MWKcTc8s4BQxXzU3zQUBIHH8pmB1932vTpNBQkCideQqJV+YAcYeU2HbpzNC3LGl09VVDMy3VwopiPIUbCctJ6fgYyZxO5JJRBxP6HbBomrHyktrHb73ckGppXrBHUp01XvNNgnvWndluYThGKw7xWqQLQjUSyNjYLRpXxK1yRfUBUKOidsSK+HUy355sd17djwBztYep13wSl42AUcsOPlfZ242H9kV2VgMgSEK8ubAWWvwFu/4z5P6IXcVI4uYEX4IyBVi3bKpymGE/FnwUqeIfYEMosi+Lfcl/9mUok0OLuoN1jq0=
node_js:
- 8.9.4
install:
- npm install
script:
- npm test
- docker tag healthcare_chat_server:latest $DOCKER_HUB_USERNAME/healthcare_chat_server:production
- docker push $DOCKER_HUB_USERNAME/healthcare_chat_server:production
- ssh -o StrictHostKeyChecking=no -i deploy_key ubuntu@<37.97.247.182 ./Public/deploy.sh

after_success:
- curl --ftp-create-dirs -T filename sftp://${SFTP_USER}:${SFTP_PASSWORD}@37.97.247.182/
before_install:
- openssl aes-256-cbc -K $encrypted_f3b59f4010df_key -iv $encrypted_f3b59f4010df_iv
  -in deploy_key.enc -out ./deploy_key -d

 deploy:
 provider: script
 skip_cleanup: true
 on:
   branch: master